# Generated by Django 5.2.12 on 2026-03-14 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='bet365', max_length=50)),
                ('odds_home', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('odds_draw', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('odds_away', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('odds_over', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('odds_under', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('over_under_line', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='espn.event')),
            ],
            options={
                'unique_together': {('event', 'provider')},
            },
        ),
    ]
