# Generated by Django 5.2.12 on 2026-03-14 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('season_type', models.PositiveSmallIntegerField(default=2, help_text='1=preseason, 2=regular, 3=postseason')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('slug', models.CharField(blank=True, max_length=64)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='espn.league')),
            ],
            options={
                'ordering': ['-year', 'season_type'],
                'unique_together': {('league', 'year', 'season_type')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='espn.season'),
        ),
    ]
