# Generated by Django 5.2.12 on 2026-03-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('espn', '0003_populate_seasons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='season_slug',
        ),
        migrations.RemoveField(
            model_name='event',
            name='season_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='season_year',
        ),
    ]
