"""Refresh the Core WADL catalog and compare it with hand-written documentation.

Run from any directory: python scripts/audit_endpoints.py
Uses only the standard library. Advertised routes are not proof of live support.
"""

import hashlib
import json
import re
import urllib.request
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NS = {"w": "http://wadl.dev.java.net/2009/02"}


def normalize(url):
    url = re.sub(r"\{[^}]+\}", "{}", url.split("?")[0].rstrip("/"))
    url = re.sub(r"(/sports/)[^/]+", r"\1{}", url)
    return re.sub(r"(/leagues/)[^/]+", r"\1{}", url)


def parse_wadl(raw, base):
    records = {}

    def walk(node, parent, inherited):
        path = parent.rstrip("/") + "/" + node.get("path", "").strip("/")
        params = inherited | {
            p.get("name") for p in node.findall("w:param", NS)
            if p.get("style") == "query"
        }
        for method in node.findall("w:method", NS):
            query = params | {
                p.get("name") for p in method.findall("w:request/w:param", NS)
                if p.get("style") == "query"
            }
            record = {
                "method": method.get("name"), "url": path.rstrip("/"),
                "id": method.get("id"), "query_parameters": sorted(query),
            }
            records[(record["method"], record["url"])] = record
        for child in node.findall("w:resource", NS):
            walk(child, path, params)

    root = ET.fromstring(raw)
    for resources in root.findall("w:resources", NS):
        for resource in resources.findall("w:resource", NS):
            walk(resource, base, set())
    return sorted(records.values(), key=lambda r: (r["url"], r["method"]))


def main():
    docs = [ROOT / "README.md", *sorted((ROOT / "docs" / "sports").glob("*.md"))]
    documented = {
        normalize(url)
        for doc in docs
        for url in re.findall(r"https://sports\.core\.api\.espn\.com/[^`\s\"<>]+", doc.read_text(encoding="utf-8"))
    }
    result = {"checked_at": datetime.now(timezone.utc).isoformat(), "sources": [], "endpoints": []}
    for version in (2, 3):
        base = f"https://sports.core.api.espn.com/v{version}"
        url = base + "/application.wadl"
        with urllib.request.urlopen(url, timeout=60) as response:
            raw = response.read()
        records = parse_wadl(raw, base)
        for record in records:
            record["in_sport_docs"] = normalize(record["url"]) in documented
        result["sources"].append({"url": url, "sha256": hashlib.sha256(raw).hexdigest(), "routes": len(records)})
        result["endpoints"].extend(records)
    out = ROOT / "docs" / "data"
    out.mkdir(exist_ok=True)
    (out / "core-endpoints.json").write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    lines = ["# Core endpoint catalog", "", f"Fetched: {result['checked_at']}", "",
             "Generated by `python scripts/audit_endpoints.py`. WADL-advertised routes may be internal, obsolete, or sport-specific; they are not individually live-verified.", "",
             "The coverage column compares explicit full URL shapes with README and sport references, normalizing sport/league names and placeholders. Relative paths and prose are not counted; 'no' is a review flag, not proof of absence. This catalog covers the two Core WADLs, not every ESPN host.", "",
             "| Method | URL | Query parameters | In sport docs |", "| --- | --- | --- | --- |"]
    for r in result["endpoints"]:
        lines.append(f"| {r['method']} | `{r['url']}` | {', '.join(r['query_parameters']) or '—'} | {'yes' if r['in_sport_docs'] else 'no'} |")
    (ROOT / "docs" / "core-endpoints.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(json.dumps({"sources": result["sources"], "missing_from_sport_docs": sum(not r["in_sport_docs"] for r in result["endpoints"])}, indent=2))


if __name__ == "__main__":
    main()
